### ISSUE TITLE
No command handling/args

### ISSUE THREAD

**Issue by TacoSnack** [mastertar/deezgunzBotJS#2]
It has no [command handling](https://discordjs.guide/command-handling/#individual-command-files) or [arguments](https://discordjs.guide/creating-your-bot/commands-with-user-input.html#basic-arguments), I'll make a pull request later with changes.

**Comment by mastertar** [comment]
wait does it allow you to edit my repos?

**Comment by mastertar** [comment]
> It has no [command handling](https://discordjs.guide/command-handling/#individual-command-files) or [arguments](https://discordjs.guide/creating-your-bot/commands-with-user-input.html#basic-arguments), I'll make a pull request later with changes.

Um, I just have this here as my original code for my bot. I have a discord.py bot with more features + command & error handling + args + api calls for images and texted based. If I do make args, it will not be soon.
